//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recurso repetido.
        /// </summary>
        public static string AlredyExistException {
            get {
                return ResourceManager.GetString("AlredyExistException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no se puede cambiar el estado ya atendido.
        /// </summary>
        public static string CannotChangeTheAlreadyAttendedStatus {
            get {
                return ResourceManager.GetString("CannotChangeTheAlreadyAttendedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha no disponible.
        /// </summary>
        public static string DateNotAvailable {
            get {
                return ResourceManager.GetString("DateNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha fuera de rango.
        /// </summary>
        public static string DateOutOfRange {
            get {
                return ResourceManager.GetString("DateOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La entidad no puede ser nula.
        /// </summary>
        public static string EntityCanNotBeNull {
            get {
                return ResourceManager.GetString("EntityCanNotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La fecha debe ser mayor a un dia.
        /// </summary>
        public static string IncorrectAppointmentDateException {
            get {
                return ResourceManager.GetString("IncorrectAppointmentDateException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credenciales incorrectas.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fecha no valida.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usted no esta autorizado.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El atributo no cumple el numero de caracteres requerido.
        /// </summary>
        public static string NumberOfCharactersRequired {
            get {
                return ResourceManager.GetString("NumberOfCharactersRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to carroo registrado.
        /// </summary>
        public static string registorarcarro {
            get {
                return ResourceManager.GetString("registorarcarro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro el recurso {0}.
        /// </summary>
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El valor ingresado no es numérico.
        /// </summary>
        public static string TheDataIsNotANumber {
            get {
                return ResourceManager.GetString("TheDataIsNotANumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La fecha no es valida.
        /// </summary>
        public static string TheDateIsNotValid {
            get {
                return ResourceManager.GetString("TheDateIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico no es válido.
        /// </summary>
        public static string TheEmailIsNotValid {
            get {
                return ResourceManager.GetString("TheEmailIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña tiene que ser diferente.
        /// </summary>
        public static string ThePasswordHasToBeDifferent {
            get {
                return ResourceManager.GetString("ThePasswordHasToBeDifferent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No puede ser menor de edad.
        /// </summary>
        public static string UnderAgeException {
            get {
                return ResourceManager.GetString("UnderAgeException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El pais no es correcto debe ser colombia.
        /// </summary>
        public static string WrongCountryException {
            get {
                return ResourceManager.GetString("WrongCountryException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El estado de la eps ya esta desabilitado.
        /// </summary>
        public static string YouCannotDisableItIsAlreadyDisabled {
            get {
                return ResourceManager.GetString("YouCannotDisableItIsAlreadyDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El estado de la eps ya esta habilitado.
        /// </summary>
        public static string YouCannotEnableItIsAlreadyEnabled {
            get {
                return ResourceManager.GetString("YouCannotEnableItIsAlreadyEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene permiso sobre este recurso.
        /// </summary>
        public static string YouDontHavePermissions {
            get {
                return ResourceManager.GetString("YouDontHavePermissions", resourceCulture);
            }
        }
    }
}
